apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-api
  name: simple-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-api
    spec:
      containers:
      - image: "ghcr.io/varianter/k8s-101:v1.1.0"
        name: api
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 3
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 1
          initialDelaySeconds: 2
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 3
          initialDelaySeconds: 3
          failureThreshold: 30
        resources: {}
status: {}
